### PR TITLE
adds new tests for hidden folders to provide means of additional file coloring 

### PR DESCRIPTION
**Pull request by jimmydburr**
Also changes colors to suit my personal preferences. Added a couple of screenshots that preview the changes.

You may not be interested in these mods at all and that's OK. I just wanted to make them available in case you were.

### CODE REVIEW

**Comment by JRJurman** [comment]
Looks great! Instead of adding the images to the repo, replace the current one in README with the two you have. 

I'm not 100% sure why the tests are failing, or what they're testing.. That work was done by @weswigham, so once those pass (or, if we could just remove them), then we can merge this in!

**Comment by JRJurman** [comment]
Actually, those tests are failing on master anyways, so we might resolve that outside of this PR. Just remove the images from the repo, and include the pictures in the README.

**Comment by jimmydburr** [comment]
Ok, JR. Sounds good. Will fix up the README with the images and get it back to you.

**Comment by jimmydburr** [comment]
JR, after quite a bit of googling/looking around the only way I see to get the images uploaded to cloud.githubusercontent.com is via creating an "issue" to drag and drop the pic into. This returns a markdown link. I can't create issues on my fork. 

Do you want me to create an issue on your repo to drop the images in? Or do you know of a better way?  Thx.

**Comment by weswigham** [comment]
@JRJurman yeah... The appveyor image and script needs to be changed. Their infrastructure has changed a bit, I think.

**Comment by JRJurman** [comment]
@jimmydburr You can actually add the images to this PR, and then copy the url from there.

**Comment by jimmydburr** [comment]
Excellent!  We'll give that a go then ;)

**Comment by jimmydburr** [comment]
powerls-on-powershell

**Comment by jimmydburr** [comment]
powerls-on-powershell-ise

**Comment by jimmydburr** [comment]
Jesse, have a look and see what you think.

**Comment by JRJurman** [comment]
Looks perfect! :+1:

**Pull request merged**
